export const initialData = [
  { id: 1, part: "Đĩa", row: "R1", formula: "MR(7X)", completed: true },
  { id: 2, part: "", row: "R2", formula: "7V", completed: true },
  { id: 3, part: "", row: "R3", formula: "(X,V)*7", completed: true },
  { id: 4, part: "", row: "R4", formula: "(X,VX)*7", completed: true },
  { id: 5, part: "", row: "R5", formula: "(3X,V)*7", completed: true },
  { id: 6, part: "", row: "R6", formula: "(2X,V,2X)*7", completed: true },
  { id: 7, part: "", row: "R7", formula: "(3X,V,3X)*7", completed: true },
  { id: 8, part: "", row: "R8", formula: "(7X,V)*7", completed: true },
  { id: 9, part: "", row: "R9", formula: "(4X,V,4X)*7", completed: true },
  { id: 10, part: "", row: "R10", formula: "(9X,V)*7", completed: true },
  { id: 11, part: "", row: "R11", formula: "(5X,V,5X)*7", completed: true },
  { id: 12, part: "", row: "R12", formula: "(11X,V)*7", completed: true },
  { id: 13, part: "", row: "R13", formula: "28X,22T,28X", completed: true },
  { id: 14, part: "", row: "R14", formula: "(6X,V,6V)*7", completed: true },
  { id: 15, part: "", row: "R15", formula: "(13X,V)*7", completed: true },
  { id: 16, part: "", row: "R16", formula: "(7X,V,7X)*7", completed: true },
  { id: 17, part: "", row: "R17 - R21", formula: "96X", completed: true },
  { id: 18, part: "", row: "R22", formula: "(7X,A,7X)*6", completed: true },
  { id: 19, part: "", row: "R23", formula: "(13X,A)*6", completed: true },
  { id: 20, part: "", row: "R24", formula: "(6X,A,6X)*6", completed: true },
  { id: 21, part: "", row: "R25", formula: "28X,22T,28X", completed: true },
  { id: 22, part: "", row: "R26", formula: "(11X,A)*6", completed: true },
  { id: 23, part: "", row: "R27", formula: "(5X,A,5X)*6", completed: false },
  { id: 24, part: "Lót trong", row: "R1", formula: "MR(7X)", completed: false },
  { id: 25, part: "", row: "R2", formula: "7V", completed: false },
  { id: 26, part: "", row: "R3", formula: "(X,V)*7", completed: false },
  { id: 27, part: "", row: "R4", formula: "(X,VX)*7", completed: false },
  { id: 28, part: "", row: "R5", formula: "(3X,V)*7", completed: false },
  { id: 29, part: "", row: "R6", formula: "(2X,V,2X)*7", completed: false },
  { id: 30, part: "", row: "R7", formula: "(3X,V,3X)*7", completed: false },
  { id: 31, part: "", row: "R8", formula: "(7X,V)*7", completed: false },
  { id: 32, part: "", row: "R9", formula: "(4X,V,4X)*7", completed: false },
  { id: 33, part: "Chân đỡ", row: "R1", formula: "MR(6X)", completed: false },
  { id: 34, part: "", row: "R2", formula: "6V", completed: false },
  { id: 35, part: "", row: "R3 - R6", formula: "12X", completed: false },
  { id: 36, part: "Tai mèo", row: "R1", formula: "MR(6X)", completed: false },
  { id: 37, part: "", row: "R2", formula: "(X,V,X)*2", completed: false },
  { id: 38, part: "", row: "R3", formula: "(X,V)*4", completed: false },
  { id: 39, part: "", row: "R4", formula: "(X,V,X)*4", completed: false },
  { id: 40, part: "", row: "R5", formula: "(3X,V)*4", completed: false },
  { id: 41, part: "", row: "R6", formula: "(2X,V,2X)*4", completed: false },
  { id: 42, part: "", row: "R7", formula: "(5X,V)*4", completed: false }
];
